In [1]:
import numpy as np

In [3]:
np.absolute(5.2)

5.2

In [4]:
np.sqrt(9)

3.0

In [5]:
vec=np.array([2,3,4])

In [6]:
vec

array([2, 3, 4])

In [8]:
vec.shape

(3,)

In [25]:
vec_new=np.array([[1,2,3],[4,5,6],[3,4,9],[2,1,0]])
vec_new.shape
vec_new

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 9],
       [2, 1, 0]])

In [22]:
vec.reshape(3,1)


array([[2],
       [3],
       [4]])

In [29]:
 vec_new.reshape(2,6)

array([[1, 2, 3, 4, 5, 6],
       [3, 4, 9, 2, 1, 0]])

# Indexing Numpy Arrays

In [30]:
M=np.arange(100).reshape(10,10)

In [31]:
M

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
M[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [34]:
M[:8,1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72]])

# Modify Array

In [42]:
M[4]=200
M

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [200, 200, 200, 200, 200, 200, 200, 200, 200, 200],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [52]:
M[2:5]+=1
M

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 29,  30,  31,  32,  33,  34,  35,  36,  37,  38],
       [ 39,  40,  41,  42,  43,  44,  45,  46,  47,  48],
       [209, 209, 209, 209, 209, 209, 209, 209, 209, 209],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [81]:
M[:5,2:3]+=1
M

array([[  0,   1,  21,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  31,  13,  14,  15,  16,  17,  18,  19],
       [ 29,  30,  56,  32,  33,  34,  35,  36,  37,  38],
       [ 39,  40,  66,  42,  43,  44,  45,  46,  47,  48],
       [209, 209, 234, 209, 209, 209, 209, 209, 209, 209],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [93]:
row_vector = np.arange(1,6)
row_vector


array([1, 2, 3, 4, 5])

In [89]:
row_vector = np.arange(11,17).reshape(6,1)
row_vector

array([[11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [91]:
M1=np.array([1,2,3,4,5,6])
M1

array([1, 2, 3, 4, 5, 6])

# Modify arrays based on the boolean values

In [95]:
M2=np.arange(7)
M2[M2%2==0]

array([0, 2, 4, 6])

In [96]:
M2[M2%2==0]=-1
M2

array([-1,  1, -1,  3, -1,  5, -1])

In [98]:
np.mean(M1)

3.5

In [100]:
M4=np.array([0.2, 0.8, 0.3, 0.6])
M4[M4>np.mean(M4)]

array([0.8, 0.6])

# Perform Linear algebra Operations

In [102]:
vec=np.arange(1,9)
vec1=2*vec
vec1

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [104]:
vec=np.array([[3,4,5,6,9],[5,6,7,21,2]])
vec+=1
vec+=vec
vec

array([[ 8, 10, 12, 14, 20],
       [12, 14, 16, 44,  6]])

In [117]:
vec.shape

(2, 5)

In [109]:
vec1.reshape(8,1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16]])

In [111]:
vec_new=np.arange(1,6).reshape(5,1)

In [113]:
vec_new.shape

(5, 1)

# vector multiplication with dot

In [116]:
vec_mul=vec.dot(vec_new)
vec_mul

array([[220],
       [294]])

# iterate over vector

In [118]:
for item in np.nditer(vec):
    print(item)

8
10
12
14
20
12
14
16
44
6


In [124]:
for i in np.nditer(vec.T, order='F'):
    print(i)

8
10
12
14
20
12
14
16
44
6


In [175]:
vec_a=np.arange(1,17).reshape(1,16)
vec_b=np.arange(1,17).reshape(1,16)

In [176]:
vec_a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [177]:
vec_b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [178]:
for item in np.nditer(vec_a):
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [179]:
print(vec_a.shape)

(1, 16)


In [180]:
ret_val=np.sum(vec_a*vec_b)
ret_val

1496

In [186]:
np.shape(vec_a)[1]
np.multiply

16

In [188]:
ret_val=np.multiply(vec_a,vec_b)
print(ret_val)

[[  1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256]]


In [190]:
ret_val.min()

1

In [192]:
vec_a.shape[0]

1

In [194]:
if vec_a.shape==vec_b.shape:
    print("Hello")

Hello


In [198]:
res=vec_a+vec_b
res

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32]])

In [200]:
np.dot(np.transpose(vec_a),vec_a)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,  39,
         42,  45,  48],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
         56,  60,  64],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
         70,  75,  80],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
         84,  90,  96],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
         98, 105, 112],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96, 104,
        112, 120, 128],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108, 117,
        126, 135, 144],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160],
       [ 11,  22,  33,  44,  5

In [201]:
from numpy.linalg import matrix_rank
matrix_rank(vec_a)

1